### ISSUE TITLE
In the local execution, impossible to load one of default two games

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#249]
I got the sources, then I followed the installation instructions (I'm on Windows 10, and Firefox). In the end, I get all three terminals.

The cover page is launched, and under the text "Commencez à jouer" I have the choice of being able to launch two games (test and pref).
I click on one of the two (I did the test with both), the "En attente d'une connection…" page appears and then nothing! The game does not start.
Also, I tried to do a "build" but this time the choice of games is empty. 

Any idea of the source of these problems?

**Comment by jrmi** [comment]
Hi Ribakys,

My first guess is that the front end works well but can't reach the backend.

- Can you reach the server by visit this URL `http://<serverIp>:<serverport>/socket.io/` with your browser ? (Look at the startup messages of server to know IP and port)
  ![image](https://user-images.githubusercontent.com/571533/108238662-71c1a700-7149-11eb-81b4-e76c7a64bd48.png)
- Double check the frontend value of the variable `REACT_APP_SOCKET_URL` inside your `.env` file
- Try to install a Cors Everywhere firefox module and disable Cors to see if it's better
- Try to proxify the server by adding `"proxy": "http://<serverIp>:<serverPort>/"` to client package.json file as described [here](https://create-react-app.dev/docs/proxying-api-requests-in-development/) and update the frontend configuration in `.env` file.
 
For the two game, this are only game visible in development mode. Even if the server is unreachable it will works and if you build, you'll not see them anymore.

If nothing works, can you paste me the content of the following files:
- .env
- backend/.env
- backend/site.json

**Comment by Ribakys** [comment]
Thank you for the answer!

I tested each point:

- When I visit the URL `http://localhost:3001/socket.io`,  I've in return a JSON response on the page : 
`message | "X-SPC-Host or Origin header is required"`
`stackTrace | "Error: ...`

- I check inside `.env` file, It's ok.

- I've installed Cors module for Firefox : nothing better.

- Try to proxify the server : nothing is happening.

The content of the following files are :
- .env
![image](https://user-images.githubusercontent.com/79149378/108275477-b57ed580-7176-11eb-9c23-4bff7222b140.png)

- backend/.env
![image](https://user-images.githubusercontent.com/79149378/108275614-e5c67400-7176-11eb-818e-14ace083ef2d.png)

- backend/site.json
![image](https://user-images.githubusercontent.com/79149378/108275666-f70f8080-7176-11eb-8c0f-fec0d6b5c990.png)

**Comment by jrmi** [comment]
Sorry, my bad, I didn't update ricochet-js on the backend. Can you try the branch "update-ricochet" and tell me if that fix your issue ?

**Comment by Ribakys** [comment]
I've update with the new code.

When I visit the URL `http://localhost:3001/socket.io`, return :
![image](https://user-images.githubusercontent.com/79149378/108430456-b0d32380-7241-11eb-87ba-246cdf0595ab.png)

And  the "En attente d'une connection…" page appears and then always nothing.

**Comment by jrmi** [comment]
I prefer the message you see.

Did you try from a fresh start on this branch ? Also sometimes browsers takes time to reconnect to a websocket, can you try in private mode ?

You can also try to use the public websocket provider by using this configuration in client `.env` file.

```
REACT_APP_SOCKET_URL=https://public.jeremiez.net/
REACT_APP_SOCKET_PATH=/wamp2/socket.io
```

**Comment by jrmi** [comment]
@Ribakys did you make it works ?

**Comment by Ribakys** [comment]
I just try it. Finally I started from scratch with the branch, and it worked well!
I can access the two basic demos.

Now, if I want to create my own game (with for example my card pictures), is there a specific procedure? Also, if the game wants to add new features, is there a procedure for this?

**Comment by jrmi** [comment]
Airboardgame is still young so there is not yet an official procedure to add a game. Just create an unpublished game first and since the game is right for you, make it public.

To add new features, create an issue ticket to start a discussion around this topic, and if the ticket is valid, you are welcome to make a PR.

**Comment by jrmi** [comment]
By the way, the branch is now merged so you can use main branch.

**Comment by Ribakys** [comment]
How `Just create an unpublished game first`

**Comment by jrmi** [comment]
I've started a quick and dirty video tutorial here https://youtu.be/Qu-j5QB76YU 
Not very finished but it should helps you.

And here is the complete process:

- First you need to login (the top right button after accepting the cookie notice).
- Since you are logged you should see the "New game" button in the top bar. Click on it to start a new game.
- To try quickly it's working well, just change the game name with the detail modal that you can open by clicking the pen in the middle of the top bar.
- Then open the save modal by clicking the disk icon on the right of the top bar and click save. It should show a green toast. (if it doesn't, try to disconnect and reconnect)
- Since you manage to save the game, you should find it with other games if you come back to the homepage. To edit it again, just click the top right corner on the pen that appear when you hover the game image. You can also start to play with it by clicking the image. It start a session you can share with your friends.
- To make the game public, open the detail modal and check the last item "Public" and save the game again. It should now be visible to all users.

Does that help ?

**Comment by Ribakys** [comment]
Thank you. I will try this !

**Comment by jrmi** [comment]
This issue is solved so I close it. Thanks for reporting.
