### ISSUE TITLE
To initialize a new game

### ISSUE THREAD

**Issue by Ribakys** [jrmi/airboardgame#275]
When we launch a game, the initialization are realized with a `.js` file as strong.

Why don't use a save file (`.json` file) to initialize the game with simply call this code (into `.js` file) of style of : `loadInitialization(myInitialization_saveFile.json)`.

This save file would be dedicated to initialization.

**Comment by jrmi** [comment]
Actually, only two games are loaded from plain `.js` file, the two tests games the js format allow us to automate some things like create 2000 identical board items (in the perf game for instance) and because it's easier to edit. Those two games are only available for dev purpose.

AFAIK, other games are loaded from the server as JSON data from a rest API. See https://github.com/jrmi/airboardgame/blob/45ba56be3f9044ee6c7ac6f018e0ef6a6a4b8e9e/src/views/GameView.js#L35 for game loading process.

May be I misunderstood your comment?

**Comment by jrmi** [comment]
What do you think of my answer ?

**Comment by Ribakys** [comment]
OK I understand.
