### ISSUE TITLE
Add shortcut to save position on board

### ISSUE THREAD

**Issue by jrmi** [jrmi/airboardgame#291]
To allow easy navigation between shortcut.

**Comment by romgar** [comment]
This feature would include:
- [ ] Create a shortcut,
- [ ] Navigate to a specific created shortcut,
- [ ] Delete a shortcut,
- [ ] Show all the current shortcuts?

**Comment by jrmi** [comment]
I'm not sure delete a shortcut is necessary if you don't need it, don't use it or replace it (can be a catch phrase :D).

"Show all shortcut" may be useful but, i think, hard to achieve (considering UX). Is it worth it?

I think something like RTS game shortcuts. `<meta>+key` to set, then `key` to go. Can be "function keys" or "number keys"...

**Comment by jrmi** [comment]
> Save position of a view, ok. And we could save also zoom level?

Yes with the zoom!

> Furthermore, can you confirm to me that we cannot rotate the view?

Yeah sorry for that. I'm not sure it will be possible to rotate one day and I'm even not sure this is a good idea for usability...

> 
> Here is a suggestion to handle view position 1 for example:
> A shortcut to save a view position like "Alt + 1" keys.
> A shortcut to go to a view location like "1" key.

I was thinking about something like that. That's what we see in RTS games.

**Comment by Ribakys** [comment]
Good. In fact, without rotation here, there resolve the problem encountered in real. When we are sit around a table (because we don't have the place), our view are not the same, and some items have an inverted view (ex. reversed card direction that are not possible to read the text).

In AirBoardGame, we don't have this disposition problem, we can have all the same view !
It feel naturel, and also, it is an advantage at the level of physical dispotition in the space.

**Comment by jrmi** [comment]
hey @Ribakys @romgar you can test this features if you want.
